version: "3.7"
services:
  frontend:
    image: frontend
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    image: backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8088:8088